experiment_dir: OOOOOO
n_forward_steps: 40
forward_steps_in_memory: 40
checkpoint_path: FFFFFF
logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace
initial_condition:
  path: /scratch4/GFDL/gfdlscr/Linjiong.Zhou/datasets/training/ufs_replay/XXxYY/training_TTTSSS.XXxYY.nc
  #path: /scratch4/GFDL/gfdlscr/Linjiong.Zhou/datasets/training/era5_reanalysis/XXxYY/training_TTTSSS.XXxYY.nc
  start_indices:
    times:
      - "YYYY-MM-DDTHH:00:00"
forcing_loader:
  dataset:
    data_path: /scratch4/GFDL/gfdlscr/Linjiong.Zhou/datasets/training/ufs_replay/XXxYY/
    #data_path: /scratch4/GFDL/gfdlscr/Linjiong.Zhou/datasets/training/era5_reanalysis/XXxYY
  num_data_workers: 4
data_writer:
  save_prediction_files: true
  save_monthly_files: false
  names: ["h200", "h500", "h850", "UGRD200", "UGRD500", "UGRD850", "VGRD200", "VGRD500", "VGRD850", "Q200", "Q500", "Q850", "TMP200", "TMP500", "TMP850", "Q2m", "TMP2m", "UGRD10m", "VGRD10m", "PRATEsfc", "PRESsfc", "HGTsfc", "sea_level_pressure", "air_temperature_3", "air_temperature_4", "air_temperature_7", "air_temperature_8", "eastward_wind_6", "eastward_wind_13", "northward_wind_6", "northward_wind_13"]
